### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinacupac** [alptium/bojana.lucic#1]
Hi @Bojana06,

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Close this ticket.
4. Go to https://github.com/orgs/alptium/teams/java-team/discussions and start doing the practical projects there (see discussions from bottom to top).

Thanks,
Valentina

**Comment by valentinacupac** [comment]
@Bojana06, please process this ticket.

**Comment by Bojana06** [comment]
I have received this ticket. 
@valentinacupac
